feat: BTD-268 env variable MAPPINGS can point to a folder now
Leadformance/mongo-postgresql-streamer pull request #7
Opened 2021-01-27 14:25 UTC by evialle73

Task BTD-268 from Epic BTD-272

The env variable MAPPINGS can point to a folder now:

- If MAPPINGS Point to a folder: all json files in this folder are loaded and aggregated by the tool internally
- If MAPPINGS Point to a single json file: the file is loaded and expected to be an aggregation of mapping files (old behavior)

I also added a `./mapping` folder in the project to perform some tests locally.

2021-01-27 14:31 UTC, aureliencousin requested changes
The pull request only contains the json files, the actual changed code is missing

2021-01-27 14:31 UTC, aureliencousin commented on mappings/bridge-alps.json
> +{
If those files are meant for testing purposes, please make this explicit (like moving them to a test/fixtures/ folder)

2021-01-27 14:31 UTC, aureliencousin commented on mappings/bridge-alps.json
> +    "_id": {
If those files are meant for testing purposes, we don't need all of them. If the goal is to be able to test the aggregation, then 2 mapping files should be enough

2021-01-27 14:59 UTC, evialle73 commented on mappings/bridge-alps.json
> +    "_id": {
They are not the same, I want all of them for later (mongodump import)

2021-01-27 15:00 UTC, evialle73 commented on mappings/bridge-alps.json
> +{
yes, I will do that

2021-01-27 15:55 UTC, evialle73 commented on mappings/bridge-alps.json
> +{
done

2021-01-27 15:55 UTC, aureliencousin commented on mappings/bridge-alps.json
> +    "_id": {
ok

2021-01-27 15:59 UTC, jeremybviseo commented on src/main/java/com/malt/mongopostgresqlstreamer/configurations/MongoConfiguration.java
> +	@Value(value = "${mongo.uri:mongodb://localhost:27017}")
issue with IDE vs original project incrementation settings

2021-01-27 15:59 UTC, aureliencousin approved these changes

2021-01-27 15:59 UTC, jeremybviseo commented on test/mappings/bridge-alps.json
> +{
🤔 why does mapping files commited ?

2021-01-27 16:02 UTC, evialle73 commented on src/main/java/com/malt/mongopostgresqlstreamer/configurations/MongoConfiguration.java
> +	@Value(value = "${mongo.uri:mongodb://localhost:27017}")
I plan to do a major cleanup later, is it ok for you ?

2021-01-27 16:03 UTC, aureliencousin commented
code looks good to me regarding current project quality.

2021-01-27 16:04 UTC, evialle73 commented on test/mappings/bridge-alps.json
> +{
those are for testing purpose only. They can be outdated, that's not an issue. They will be important later to test the mongodump import

2021-01-27 16:29 UTC, jeremybviseo commented on src/main/java/com/malt/mongopostgresqlstreamer/configurations/MongoConfiguration.java
> +	@Value(value = "${mongo.uri:mongodb://localhost:27017}")
ok

2021-01-27 16:29 UTC, jeremybviseo commented on test/mappings/bridge-alps.json
> +{
ok

2021-01-28 08:18 UTC, aureliencousin requested changes

2021-01-28 08:18 UTC, aureliencousin commented on src/main/java/com/malt/mongopostgresqlstreamer/StreamerApplication.java
> +				.collect(Collectors.toList());
please remove this unfinished function from this PR (it's not relevant regarding commit description)

2021-01-28 09:27 UTC, closed without merging